### ISSUE TITLE
Duplicate key in gitlab.yml

### ISSUE THREAD

**Issue by ErwinJunge** [tiredofit/docker-gitlab-ee#1]
There's a duplicate key `elastic_index_initial_bulk_cron_worker` in the gitlab.yml file here: https://github.com/tiredofit/docker-gitlab-ee/blob/b1d70d437a10e5334535074c16977160b81d3cc8/install/assets/gitlab/config/gitlabhq/gitlab.yml#L414

**Comment by tiredofit** [comment]
Thanks for this! I'm going to go with the /10 one, Running every minute seems excessive.

**Comment by ErwinJunge** [comment]
You're welcome :) It's the free code-review you get for pointing me over here in https://github.com/sameersbn/docker-gitlab/pull/2329 :+1:
